version: '3.8'

services:
  fayda-wallet:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  # For development with hot reload
  fayda-wallet-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "19000:19000"  # Expo dev server
      - "19001:19001"  # Expo dev tools
      - "19002:19002"  # Metro bundler
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: npm start
    profiles:
      - dev